const info = {
  info1: '$blue1',
  info2: '$blue2',
  info3: '$blue3',
  info4: '$blue4',
  info5: '$blue5',
  info6: '$blue6',
  info7: '$blue7',
  info8: '$blue8',
  info9: '$blue9',
  info10: '$blue10',
  info11: '$blue11',
  info12: '$blue12',
};
const error = {
  success1: '$success1',
  success2: '$success2',
  success3: '$success3',
  success4: '$success4',
  success5: '$success5',
  success6: '$success6',
  success7: '$success7',
  success8: '$success8',
  success9: '$success9',
  success10: '$success10',
  success11: '$success11',
  success12: '$success12',
};
const warn = {
  warn1: '$yellow1',
  warn2: '$yellow2',
  warn3: '$yellow3',
  warn4: '$yellow4',
  warn5: '$yellow5',
  warn6: '$yellow6',
  warn7: '$yellow7',
  warn8: '$yellow8',
  warn9: '$yellow9',
  warn10: '$yellow10',
  warn11: '$yellow11',
  warn12: '$yellow12',
};
const success = {
  success1: '$green1',
  success2: '$green2',
  success3: '$green3',
  success4: '$green4',
  success5: '$green5',
  success6: '$green6',
  success7: '$green7',
  success8: '$green8',
  success9: '$green9',
  success10: '$green10',
  success11: '$green11',
  success12: '$green12',
};

export const semanticColors = {
  ...error,
  ...info,
  ...success,
  ...warn,
};
